version: '3.6'

services:
  vsftpd-s3:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/vsftpd-s3
      context: ../..
      dockerfile: docker/vsftpd-s3/Dockerfile
    cap_add:
    - sys_admin
    container_name: ${HOST_COMPOSE_PROJECT_NAME}-vsftpd-s3
    devices:
    - /dev/fuse
    environment:
    - AWS_ACCESS_KEY_ID=${HOST_VSFTPD_S3_AWS_ACCESS_KEY_ID:-${AWS_ACCESS_KEY_ID}}
    - AWS_SECRET_ACCESS_KEY=${HOST_VSFTPD_S3_AWS_SECRET_ACCESS_KEY:-${AWS_SECRET_ACCESS_KEY}}
    - DIR_REMOTE=${HOST_VSFTPD_S3_DIR_REMOTE}
    - FTP_HOST=${HOST_VSFTPD_S3_FTP_HOST}
    - FTP_PASS=${HOST_VSFTPD_S3_FTP_PASS}
    - FTP_SYNC=${HOST_VSFTPD_S3_FTP_SYNC}
    - FTP_USER=${HOST_VSFTPD_S3_FTP_USER}
    - FTPD_USER=${HOST_VSFTPD_S3_FTPD_USER}
    - FTPD_USERS=${HOST_VSFTPD_S3_FTPD_USERS}
    - PASV_MAX_PORT=${HOST_VSFTPD_S3_PASV_MAX_PORT}
    - PASV_MIN_PORT=${HOST_VSFTPD_S3_PASV_MIN_PORT}
    hostname: ${HOSTNAME}
    image: ${HOST_DOCKER_REPOSITORY}/vsftpd-s3:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_21_CHECK_TCP=true
    - SERVICE_21_NAME=${HOST_COMPOSE_SERVICE_NAME}-vsftpd-s3-21
    - SERVICE_22_CHECK_TCP=true
    - SERVICE_22_NAME=${HOST_COMPOSE_SERVICE_NAME}-vsftpd-s3-22
    - SERVICE_65000_IGNORE=true
    security_opt:
    - apparmor:unconfined
    network_mode: host
    restart: always
