---
# file: meta/main.yml

dependencies: []
galaxy_info:
  author: Yann Autissier
  categories:
    - system
  description: Interact with remote services
  license: GPL
  platforms:
  - name: Alpine
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all

