version: '3.6'

services:
  alertmanager:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/alertmanager
      - SLACK_WEBHOOK_ID=${ALERTMANAGER_SLACK_WEBHOOK_ID}
      context: ../..
      dockerfile: docker/alertmanager/Dockerfile
    image: ${DOCKER_REPOSITORY}/alertmanager:${DOCKER_IMAGE_TAG}
    labels:
    - SERVICE_9093_NAME=${COMPOSE_SERVICE_NAME}-alertmanager-9093
    - SERVICE_9093_CHECK_TCP=true
    - SERVICE_9093_CHECK_INITIAL_STATUS=passing
    - SERVICE_9093_TAGS=${ALERTMANAGER_SERVICE_9093_TAGS}
    networks:
    - private
    - public
    ports:
    - 9093
    restart: always

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}
