version: '3.6'

services:
  zen:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/zen
      - GID=${GID}
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      - IPFS_VERSION=${IPFS_VERSION}
      - UID=${UID}
      - USER=${USER}
      context: ../..
      dockerfile: docker/zen/Dockerfile
    depends_on:
    - ipfs
    environment:
    - ENV=${ENV}
    - SHELL=${DOCKER_SHELL}
    - SSH_AUTH_SOCK=/tmp/ssh-agent/socket
    image: ${DOCKER_REPOSITORY}/zen:${DOCKER_IMAGE_TAG}
    networks:
    - private
    restart: always
    user: ${UID}:${GID}
    volumes:
    - astroport:${HOME}/astroport:cached
    - ipfs:${HOME}/.ipfs:cached,ro
    - myos:/tmp/ssh-agent:ro
    - zen:${HOME}/.zen:delegated
    working_dir: ${HOME}/.zen

volumes:
  astroport:
  ipfs:
    external: true
  myos:
    external: true
    name: ${USER_DOCKER_VOLUME}
  zen:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/.zen
      o: bind

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}
