---
# file: tasks/services.yml

- name: services - enable/disable remotes services
  when: remotes_services is defined and ansible_service_mgr|lower != "openrc" and ansible_service_mgr|lower != "runit"
  with_items: "{{ remotes_services|default([]) }}"
  service:
    name: "{{item.name}}"
    state: "{{item.state}}"
    enabled: "{{item.enabled}}"
  become: yes

- name: services - enable/disable remotes services - openrc
  when: remotes_services is defined and ansible_service_mgr|lower == "openrc"
  with_items: "{{ remotes_services|default([]) }}"
  service:
    name: "{{item.name}}"
    state: "{{item.state}}"
    enabled: "{{item.enabled}}"
    runlevel: boot
  become: yes

- name: services - enable/disable remotes services - runit
  when: remotes_services is defined and ansible_service_mgr|lower == "runit"
  with_items: "{{ remotes_services|default([]) }}"
  sysvinit:
    name: "{{item.name}}"
    state: "{{item.state}}"
    enabled: "{{item.enabled}}"
  become: yes

