---
# file: tasks/user.yml

- name: user - set home directory
  when: "not aws_user == 'root'"
  set_fact:
    home_dir: /home/{{ aws_user }}

- name: user - set home directory for root
  when: "aws_user == 'root'"
  set_fact:
    home_dir: /root

- name: user - create AWS config directory
  file: >
    path={{ home_dir }}/.aws
    state=directory
    owner={{ aws_user }}
    group={{ aws_group }}
    mode=0750
  become: yes

- name: user - copy AWS config file
  template: >
    src=aws_config.j2
    dest={{ home_dir }}/.aws/config
    owner={{ aws_user }}
    group={{ aws_group }}
    mode=0640
    force=yes
  become: yes

- name: user - copy AWS credentials file
  template: >
    src=aws_credentials.j2
    dest={{ home_dir }}/.aws/credentials
    owner={{ aws_user }}
    group={{ aws_group }}
    mode=0600
    force=yes
  become: yes

