version: '3.6'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.3
    environment:
    - ELASTICSEARCH_URL="${ELASTICSEARCH_PROTOCOL:-http}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}"
