version: '3.6'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
    - ELASTICSEARCH_HOSTS="${ELASTICSEARCH_PROTOCOL:-http}://${ELASTICSEARCH_HOST:-elasticsearch}:${ELASTICSEARCH_PORT:-9200}"
    - KIBANA_INDEX=.kibana.${COMPOSE_SERVICE_NAME}
    - SERVER_NAME=kibana.${APP_HOST}
