---
# file: tasks/main.yml

- import_tasks: vars.yml
  tags:
    - vars
- import_tasks: config.yml
  tags:
    - config
- import_tasks: packages.yml
  tags:
    - packages
- import_tasks: services.yml
  tags:
    - services
- import_tasks: disks.yml
  tags:
    - disks
- import_tasks: partitions.yml
  tags:
    - partitions
- import_tasks: filesystems.yml
  tags:
    - filesystems
- import_tasks: mount.yml
  tags:
    - mount
- meta: flush_handlers

