---
# file: tasks/partitions.yml

- name: partitions - extend additional disks partitions
  with_items: '{{ disks_to_mount }}'
  shell: |
    if
        [ -b {{ item.disk }} ]
    then
        [ -b {{ item.part | default(item.disk + "1") }} ] || parted -a optimal --script "{{ item.disk }}" mklabel gpt mkpart primary {{ disks_offset.stdout|default("2048") }}s 100% && sleep 5 && partprobe {{ item.disk }}; sleep 5
    fi
  args:
    creates: '{{ item.part | default(item.disk + "1") }}'
    executable: '/bin/bash'
  become: yes

- name: partitions - get UUID
  when: item.1.stat.exists
  with_together:
    - '{{ disks_to_mount }}'
    - '{{ disks_stat.results }}'
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/sbin:/sbin"
  command: blkid -s UUID -o value {{ item.0.part | default(item.0.disk + "1") }}
  changed_when: False
  check_mode: no
  become: yes
  register: disks_blkid

