version: "3.6"

services:
  restic:
    image: mazzolino/restic:1.1.1
    hostname: ${HOSTNAME}
    environment:
      BACKUP_CRON: "30 3 * * *"
      RESTIC_REPOSITORY: ${NODE_RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${NODE_RESTIC_PASSWORD}
      RESTIC_BACKUP_SOURCES: /var/lib/docker/volumes
      RESTIC_BACKUP_TAGS: docker-volumes
      RESTIC_FORGET_ARGS: --prune --keep-last 14 --keep-daily 1
      TZ: Europe/Paris
    networks:
    - private
    volumes:
      - restic:/root/.config
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro

volumes:
  restic:

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}
