version: '3.6'

services:
  registrator:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/registrator
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      context: ../..
      dockerfile: docker/registrator/Dockerfile
    container_name: ${NODE_COMPOSE_PROJECT_NAME}-registrator
    image: ${NODE_DOCKER_REPOSITORY}/registrator:${DOCKER_IMAGE_TAG}
    command: -internal -cleanup -deregister always -resync=30 -useIpFromNetwork "${DOCKER_NETWORK_PUBLIC}" -useIpFromLabel SERVICE_ADDRESS consul://consul:8500
    depends_on:
    - consul
    environment:
    - CONSUL_HTTP_TOKEN=${NODE_CONSUL_HTTP_TOKEN}
    - GL_DISABLE_VERSION_CHECK=true
    extra_hosts:
    - consul:${DOCKER_INTERNAL_DOCKER_HOST}
    hostname: ${HOSTNAME}
    network_mode: host
    restart: always
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock

networks:
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}
