version: '3.6'

services:
  myos:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/myos
      - GID=${GID}
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      - IPFS_VERSION=${IPFS_VERSION}
      - UID=${UID}
      - USER=${USER}
      - SSH_BASTION_HOSTNAME=${SSH_BASTION_HOSTNAME}
      - SSH_BASTION_USERNAME=${SSH_BASTION_USERNAME}
      - SSH_PUBLIC_HOSTS=${SSH_PUBLIC_HOSTS}
      - SSH_PRIVATE_IP_RANGE=${SSH_PRIVATE_IP_RANGE}
      context: ../..
      dockerfile: docker/myos/Dockerfile
    container_name: ${USER_DOCKER_NAME}
    environment:
    - ENV=${ENV}
    - RC_00_SOURCE=${USER_MYOS_RC_SOURCE}
    - RC_01_PS1_SET=${USER_MYOS_RC_PS1_SET}
    - RC_02_PROMPT_SET=${USER_MYOS_RC_PROMPT_SET}
    - RC_03_SSH_ADD=${USER_MYOS_RC_SSH_ADD}
    - RC_04_TMUX_ATTACH=${USER_MYOS_RC_TMUX_ATTACH}
    - RC_05_SCREEN_ATTACH=${USER_MYOS_RC_SCREEN_ATTACH}
    - SHELL=${DOCKER_SHELL}
    image: ${USER_DOCKER_IMAGE}
    networks:
    - private
    restart: always
    user: ${UID}:${GID}
    volumes:
#     - ${HOME}:${HOME}:cached
    - monorepo:${MONOREPO_DIR}:cached
    - myos:/tmp/ssh-agent
#     - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${MONOREPO_DIR}

volumes:
  monorepo:
    driver: local
    driver_opts:
      type: none
      device: ${MONOREPO_DIR}
      o: bind
    name: ${USER_COMPOSE_PROJECT_NAME}
  myos:
    external: true
    name: ${USER_DOCKER_VOLUME}

networks:
  private:
    external: true
    name: ${DOCKER_NETWORK_PRIVATE}
