version: '3.8'

services:
  vdi:
    build:
      args:
      - DOCKER_BUILD_DIR=docker/x2go/xfce-debian
      - SSH_PORT=${NODE_VDI_PORT:-22}
      context: ../..
      dockerfile: docker/x2go/xfce-debian/Dockerfile
    cap_add:
    - IPC_LOCK # ecryptfs
    - NET_ADMIN # iptables
    - NET_RAW # iptables
    - SYS_ADMIN # ecryptfs
    container_name: ${NODE_COMPOSE_PROJECT_NAME}-vdi
    cpus: 0.5
    environment:
    - DEBUG=${VDI_DEBUG:-}
    - ECRYPTERS=${NODE_VDI_ECRYPTERS:-}
    - LANG=${NODE_VDI_LANG:-}
    - SSH_PORT=${NODE_VDI_PORT:-22}
    - SSH_AUTHORIZED_KEYS=${SSH_AUTHORIZED_KEYS:-}
    - SSH_PUBLIC_HOSTS=${NODE_SSH_PUBLIC_HOSTS:-}
    - SUDOERS=${NODE_VDI_SUDOERS:-}
    - TZ=${NODE_VDI_TZ:-}
    - USERS=${NODE_VDI_USERS:-}
    image: ${NODE_DOCKER_REPOSITORY}/vdi:${DOCKER_IMAGE_TAG}
    networks:
    - public
    ports:
    - ${NODE_VDI_PORT:-22}:${SSH_PORT:-22}
    restart: unless-stopped
    security_opt:
    - apparmor=unconfined # ecryptfs
    - seccomp=unconfined # ecryptfs
    tty: true
    volumes:
    - home:/home:delegated
    - shared:/shared:cached
    - shm:/dev/shm:delegated

networks:
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}

volumes:
  home:
  shared:
    driver: local
    driver_opts:
      type: none
      device: /mnt/shared
      o: bind
  shm:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: mode=1777,size=2147483648 # 2GB
