---
# file: tasks/config.yml

- name: config - set MYOS config in /etc/default/myos
  with_items:
  - APP_TYPE={{ lookup('env','ANSIBLE_APP_TYPE') }}
  - MYOS={{ lookup('env','ANSIBLE_MYOS') }}
  lineinfile:
    path: /etc/default/myos
    create: yes
    line: '{{ item }}'
    mode: '0644'
  become: yes

