---
# file: tasks/check.yml

- name: check - kernel version
  when: ansible_kernel is version(docker_check_kernel, "<")
  fail:
    msg: >
      docker requires a minimum kernel version of {{docker_check_kernel}}
      on {{ansible_distribution}} {{ansible_distribution_version}}

