---
# file: tasks/config.yml

- name: config - add docker storage setup
  notify: restart docker
  lineinfile: dest="{{docker_init_config_directory}}/{{docker_package}}-storage-setup" state="present" line="STORAGE_DRIVER=\"\""
  when: docker_package|length > 0 and ansible_service_mgr == "systemd" and ansible_os_family|lower == "redhat"
  become: yes

- name: config - register docker_daemon_config
  set_fact:
    docker_daemon_config: "{{ lookup('file',docker_daemon_config_file)|default('{}')|from_json}}"
  ignore_errors: true

- name: config - add docker daemon storage configuration for btrfs
  notify: restart docker
  template:
    src: daemon.json.j2
    dest: "{{docker_daemon_config_file}}"
    owner: root
    group: docker
    mode: "0640"
  when: docker_package|length > 0
  become: yes

# - name: config - disable docker iptables setup
#   lineinfile: dest="/lib/systemd/system/docker.service" state="present" regex="^ExecStart=" line="ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --iptables=false"
#   notify: restart docker
#   when: docker_package|length > 0 and ansible_service_mgr == "systemd"
#   become: yes

- name: config - setup docker mtu on Openstack VMs
  notify: restart docker
  lineinfile: dest="{{docker_init_config_directory}}/{{docker_package}}" state="present" backrefs=true regexp='^{{docker_opts}}=(?:\'|\")?((?:\s*[\w=\/\-\.](?<!--mtu=1450)\s*)*)(?:\'|\")?$' line='{{docker_opts}}="\1 --mtu=1450"'
  when: docker_package|length > 0 and ansible_product_name == "OpenStack Nova"
  become: yes
