---
# file: tasks/files.yml

- name: files - copy sysctl configuration files
  with_items:
    - /etc/sysctl.d/docker.conf
  copy: src=../files/{{item}} dest={{item}} owner=root group=root mode=0644
  become: yes

