---
# file: tasks/groups.yml

- name: groups - create docker group
  when: ansible_os_family|lower != "alpine"
  group: name="docker" state="present" system="yes"
  become: yes

- name: groups - add me to the docker group
  when: ansible_os_family|lower != "alpine" and ansible_user_uid != "0"
  user: name="{{ansible_user_id}}" groups=docker append=yes
  become: yes

