---
# file: tasks/main.yml

- import_tasks: vars.yml
  tags:
    - vars
- import_tasks: check.yml
  tags:
    - check
- import_tasks: config.yml
  tags:
    - config
- import_tasks: files.yml
  tags:
    - files
- import_tasks: packages.yml
  tags:
    - packages
- import_tasks: services.yml
  tags:
    - services
- import_tasks: groups.yml
  tags:
    - groups
- import_tasks: build.yml
  tags:
    - build
- import_tasks: run.yml
  tags:
    - run
- import_tasks: myos.yml
  when: docker_myos|default(false)
  tags:
    - myos

