---
# file: tasks/main.yml

- import_tasks: vars.yml
  tags:
    - vars
- import_tasks: check.yml
  tags:
    - check
- import_tasks: files.yml
  tags:
    - files
- import_tasks: package.yml
  tags:
    - package
- import_tasks: config.yml
  tags:
    - config
- import_tasks: service.yml
  tags:
    - service
- import_tasks: group.yml
  tags:
    - group
- import_tasks: build.yml
  tags:
    - build
- import_tasks: run.yml
  tags:
    - run
