---
# file: tasks/myos_ec2.yml

- name: myos_ec2 - get instance metadata
  ec2_metadata_facts:

- name: myos_ec2 - get instance tags
  when: ansible_ec2_instance_id is defined
  ec2_tag:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ ansible_ec2_instance_id }}"
    state: list
  register: myos

- name: myos_ec2 - ecr login
  when: myos.tags is defined
  shell: "$(aws ecr get-login --no-include-email --region {{ aws_region }})"

