---
# file: tasks/packages.yml

- name: packages - install/remove docker packages
  when: docker_packages is defined
  with_items: "{{ docker_packages|default([]) }}"
  package: name="{{item.name}}" state="{{item.state}}"
  become: yes

- import_tasks: packages_debian.yml
  when: ansible_os_family|lower == "debian"
  tags:
  - debian

- name: packages - add docker package
  when: docker_package|length > 0
  package: name="{{docker_package}}" state=present
  become: yes

