---
# file: playbook.yml

# bootstrap hosts
- hosts: default
  gather_facts: false
  pre_tasks:
  - name: raw - install ansible requirements for alpine linux
    raw: "[ -f /etc/alpine-release ] && /sbin/apk update && { which python3 >/dev/null 2>&1 || /sbin/apk add python3; } && { /bin/tar --version 2>/dev/null |grep busybox >/dev/null && /sbin/apk add tar; } && { ls /usr/lib/ssh/sftp-server >/dev/null 2>&1 || /sbin/apk add openssh-sftp-server; } || true"
  tags:
  - bootstrap

# install packages and user settings
- import_playbook: playbooks/hosts.yml

# config remotes
- import_playbook: playbooks/remotes.yml

# mount additional disks
- import_playbook: playbooks/disks.yml

# install docker
- import_playbook: playbooks/docker.yml

# launch myos
# - import_playbook: playbooks/myos.yml
