version: '3.6'

services:
  cadvisor-exporter:
    container_name: ${NODE_COMPOSE_PROJECT_NAME}-cadvisor-exporter
    hostname: ${HOSTNAME}
    image: google/cadvisor:latest
    labels:
    - SERVICE_8080_CHECK_TCP=true
    - SERVICE_8080_NAME=${NODE_COMPOSE_SERVICE_NAME}-cadvisor-exporter:8080
    - SERVICE_8080_TAGS=${NODE_CADVISOR_EXPORTER_SERVICE_8080_TAGS}
    - SERVICE_9200_IGNORE=true
    networks:
    - public
    ports:
    - 8080
    restart: always
    volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/run:/var/run:rw
  node-exporter:
    command:
    - --collector.filesystem.ignored-mount-points
    - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    - '--path.procfs=/host/proc'
    - '--path.sysfs=/host/sys'
    container_name: ${NODE_COMPOSE_PROJECT_NAME}-node-exporter
    hostname: ${HOSTNAME}
    image: prom/node-exporter:latest
    labels:
    - SERVICE_9100_CHECK_TCP=true
    - SERVICE_9100_NAME=${NODE_COMPOSE_SERVICE_NAME}-node-exporter:9100
    - SERVICE_9100_TAGS=${NODE_EXPORTER_SERVICE_9100_TAGS}
    networks:
    - public
    ports:
    - 9100
    restart: always
    volumes:
    - /:/rootfs:ro
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro

networks:
  public:
    external: true
    name: ${DOCKER_NETWORK_PUBLIC}
